osx_image: xcode10
language: objective-c
rvm:
- 2.4.1
podfile: Podfile
before_install:
- openssl aes-256-cbc -K $encrypted_f53fc276abe9_key -iv $encrypted_f53fc276abe9_iv
  -in APIKey.plist.enc -out Resources/APIKey.plist -d
- bundle install
- pod repo update
- pod install
script:
- bundle exec fastlane test_all
- bundle exec danger
after_success:
- bash <(curl -s https://codecov.io/bash) -J 'CCNumberValidator'
